<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container3sm1ofa\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container3sm1ofa/appProdProjectContainer.php') {
    touch(__DIR__.'/Container3sm1ofa.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\Container3sm1ofa\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \Container3sm1ofa\appProdProjectContainer([
    'container.build_hash' => '3sm1ofa',
    'container.build_id' => '75289fef',
    'container.build_time' => 1572674083,
], __DIR__.\DIRECTORY_SEPARATOR.'Container3sm1ofa');
