<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container2wjiudy\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container2wjiudy/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/Container2wjiudy.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\Container2wjiudy\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \Container2wjiudy\appDevDebugProjectContainer([
    'container.build_hash' => '2wjiudy',
    'container.build_id' => '79a5f554',
    'container.build_time' => 1566910278,
], __DIR__.\DIRECTORY_SEPARATOR.'Container2wjiudy');
