<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerPyq1qpb\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerPyq1qpb/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerPyq1qpb.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerPyq1qpb\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerPyq1qpb\appDevDebugProjectContainer([
    'container.build_hash' => 'Pyq1qpb',
    'container.build_id' => 'c7a5d8d7',
    'container.build_time' => 1551346893,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerPyq1qpb');
